services:
  database-postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    expose:
      - 5432

  nestjsinit:
    image: nestjsinit
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      PORT=3000
    ports:
      3000:3000
    depends_on:
      postgres
    links:
      postgres:postgres
    volumes:
      .:/usr/src/app
      /usr/src/app/node_modules
    command: npm run start:dev

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
